name: muse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30419
title: My First site on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e1c7ba'
    - '#a34808'
    - '#bc9276'
    - '#630b04'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
